version: '2'
services:
  config:
    network_mode: "host"
    restart: "always"
    build: 
      context: .
      args:
        ENCRYPT_KEY: ${ENCRYPT_KEY}
    image: config-server
    volumes:
      - /security:/security
    environment:
      TZ: "Europe/Amsterdam"
