server:
    port: 5678

spring:
    profiles:
        active:
            - prod
    application:
        name: config
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/TimGundmann/gundmann-config
                    username: ${GITHUB_USERNAME}
                    password: ${GITHUB_TOKEN}

    # boot:
    #     admin:
    #         client:
    #             username: tim
    #             password: '{cipher}5930ce1dd8cff9d0fe9002ea488964786df68ecc021528ad6af46617da54c98c'
    #             url: http://192.168.1.100:2222/admin
    #             instance:
    #                 management-base-url: http://192.168.1.100:5678
    #                 service-url: http://192.168.1.100:5678

encrypt:
    key: YcDAQ2ZVzEQDtG3cwb9WqevM5kYVwUxoAfXMjtbJpYc=

management:
    endpoints:
        web:
            exposure:
                include: '*'