name: Build Spring Boot App and Deploy Docker Image to Linux

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 23

      - name: Build Spring Boot App
        run: mvn clean package -DskipTests

      - name: Build Docker Image
        run: docker build -t config-service:latest .

      - name: Save Docker Image to File
        run: docker save config-service:latest | gzip > config-service.tar.gz

      - name: Copy Image to Remote Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "config-service.tar.gz"
          target: "/tmp"

      - name: Deploy on Remote Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker load < /tmp/config-service.tar.gz
            docker stop config-service || true
            docker rm config-service || true
            docker run -d --name config-service -p 5678:5678 config-service:latest
